# Site settings
title: Darjix
description: >-
  Welcome to Darjix.com - a modern static site built with Jekyll and Tailwind CSS.
baseurl: "/darjix" # the subpath of your site, e.g. /blog
url: "https://saldarji.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages specific settings
# Note: 'theme' is commented out since we're using custom layouts
# theme: minima

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Collections (optional - uncomment if you need them)
# collections:
#   posts:
#     output: true
#     permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

