# Site settings
title: DARJIX
description: >-
  A site about AI and education technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darjix.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages specific settings
# Note: 'theme' is commented out since we're using custom layouts
# theme: minima

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - scripts/
  - venv/
  - .github/

# Blog settings
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

