version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: sh -c "npm install && bundle install && concurrently 'npm run watch:css' 'bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling'"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    working_dir: /srv/jekyll

volumes:
  bundle_cache:

